//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellClaimService
{
    using System;
    using System.Collections.Generic;
    
    public partial class lossInfo
    {
        public lossInfo()
        {
            this.mitchellClaims = new HashSet<mitchellClaim>();
        }
    
        public int LossInfoId { get; set; }
        public int CauseOfLossId { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public string LossDescription { get; set; }
    
        public virtual causeOfLossCode causeOfLossCode { get; set; }
        public virtual ICollection<mitchellClaim> mitchellClaims { get; set; }
    }
}
