//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellClaimService
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitchellClaim
    {
        public mitchellClaim()
        {
            this.vehicleInfoes = new HashSet<vehicleInfo>();
        }
    
        public string ClaimNumber { get; set; }
        public string ClaimantFirstName { get; set; }
        public string ClaimantLastName { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
        public Nullable<decimal> AssignedAdjusterID { get; set; }
        public Nullable<int> LossInfoId { get; set; }
    
        public virtual lossInfo lossInfo { get; set; }
        public virtual statusCode statusCode { get; set; }
        public virtual ICollection<vehicleInfo> vehicleInfoes { get; set; }
    }
}
