//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellClaimService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MitchellClaimsDbEntities : DbContext
    {
        public MitchellClaimsDbEntities()
            : base("name=MitchellClaimsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<causeOfLossCode> causeOfLossCodes { get; set; }
        public virtual DbSet<lossInfo> lossInfoes { get; set; }
        public virtual DbSet<mitchellClaim> mitchellClaims { get; set; }
        public virtual DbSet<statusCode> statusCodes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vehicleInfo> vehicleInfoes { get; set; }
    }
}
