//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MitchellClaimClient.MitchellService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MitchellFault", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class MitchellFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MitchellClaim", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class MitchellClaim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AssignedAdjusterIDField;
        
        private string ClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimantFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimantLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LossDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MitchellClaimClient.MitchellService.LossInfo LossInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MitchellClaimClient.MitchellService.StatusCode StatusField;
        
        private System.Collections.Generic.List<MitchellClaimClient.MitchellService.VehicleDetails> VehiclesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AssignedAdjusterID {
            get {
                return this.AssignedAdjusterIDField;
            }
            set {
                if ((this.AssignedAdjusterIDField.Equals(value) != true)) {
                    this.AssignedAdjusterIDField = value;
                    this.RaisePropertyChanged("AssignedAdjusterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClaimNumber {
            get {
                return this.ClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNumberField, value) != true)) {
                    this.ClaimNumberField = value;
                    this.RaisePropertyChanged("ClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimantFirstName {
            get {
                return this.ClaimantFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimantFirstNameField, value) != true)) {
                    this.ClaimantFirstNameField = value;
                    this.RaisePropertyChanged("ClaimantFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimantLastName {
            get {
                return this.ClaimantLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimantLastNameField, value) != true)) {
                    this.ClaimantLastNameField = value;
                    this.RaisePropertyChanged("ClaimantLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LossDate {
            get {
                return this.LossDateField;
            }
            set {
                if ((this.LossDateField.Equals(value) != true)) {
                    this.LossDateField = value;
                    this.RaisePropertyChanged("LossDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MitchellClaimClient.MitchellService.LossInfo LossInfo {
            get {
                return this.LossInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LossInfoField, value) != true)) {
                    this.LossInfoField = value;
                    this.RaisePropertyChanged("LossInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MitchellClaimClient.MitchellService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<MitchellClaimClient.MitchellService.VehicleDetails> Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LossInfo", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LossInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MitchellClaimClient.MitchellService.CauseOfLossCode CauseOfLossField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReportedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MitchellClaimClient.MitchellService.CauseOfLossCode CauseOfLoss {
            get {
                return this.CauseOfLossField;
            }
            set {
                if ((this.CauseOfLossField.Equals(value) != true)) {
                    this.CauseOfLossField = value;
                    this.RaisePropertyChanged("CauseOfLoss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossDescription {
            get {
                return this.LossDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LossDescriptionField, value) != true)) {
                    this.LossDescriptionField = value;
                    this.RaisePropertyChanged("LossDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportedDate {
            get {
                return this.ReportedDateField;
            }
            set {
                if ((this.ReportedDateField.Equals(value) != true)) {
                    this.ReportedDateField = value;
                    this.RaisePropertyChanged("ReportedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.Utils")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OPEN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLOSED = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleDetails", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class VehicleDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DamageDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngineDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExteriorColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicPlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LicPlateExpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicPlateStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DamageDescription {
            get {
                return this.DamageDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DamageDescriptionField, value) != true)) {
                    this.DamageDescriptionField = value;
                    this.RaisePropertyChanged("DamageDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngineDescription {
            get {
                return this.EngineDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EngineDescriptionField, value) != true)) {
                    this.EngineDescriptionField = value;
                    this.RaisePropertyChanged("EngineDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExteriorColor {
            get {
                return this.ExteriorColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ExteriorColorField, value) != true)) {
                    this.ExteriorColorField = value;
                    this.RaisePropertyChanged("ExteriorColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicPlate {
            get {
                return this.LicPlateField;
            }
            set {
                if ((object.ReferenceEquals(this.LicPlateField, value) != true)) {
                    this.LicPlateField = value;
                    this.RaisePropertyChanged("LicPlate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LicPlateExpDate {
            get {
                return this.LicPlateExpDateField;
            }
            set {
                if ((this.LicPlateExpDateField.Equals(value) != true)) {
                    this.LicPlateExpDateField = value;
                    this.RaisePropertyChanged("LicPlateExpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicPlateState {
            get {
                return this.LicPlateStateField;
            }
            set {
                if ((object.ReferenceEquals(this.LicPlateStateField, value) != true)) {
                    this.LicPlateStateField = value;
                    this.RaisePropertyChanged("LicPlateState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeDescription {
            get {
                return this.MakeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeDescriptionField, value) != true)) {
                    this.MakeDescriptionField = value;
                    this.RaisePropertyChanged("MakeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelDescription {
            get {
                return this.ModelDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelDescriptionField, value) != true)) {
                    this.ModelDescriptionField = value;
                    this.RaisePropertyChanged("ModelDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelYear {
            get {
                return this.ModelYearField;
            }
            set {
                if ((this.ModelYearField.Equals(value) != true)) {
                    this.ModelYearField = value;
                    this.RaisePropertyChanged("ModelYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vin {
            get {
                return this.VinField;
            }
            set {
                if ((object.ReferenceEquals(this.VinField, value) != true)) {
                    this.VinField = value;
                    this.RaisePropertyChanged("Vin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CauseOfLossCode", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.Utils")]
    public enum CauseOfLossCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collision = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Explosion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fire = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hail = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MechanicalBreakdown = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MitchellService.IMitchellClaimService")]
    public interface IMitchellClaimService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/CreateClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/CreateClaimResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MitchellClaimClient.MitchellService.MitchellFault), Action="http://tempuri.org/IMitchellClaimService/CreateClaimMitchellFaultFault", Name="MitchellFault", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
        void CreateClaim(string createxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/CreateClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/CreateClaimResponse")]
        System.Threading.Tasks.Task CreateClaimAsync(string createxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/GetClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/GetClaimResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MitchellClaimClient.MitchellService.MitchellFault), Action="http://tempuri.org/IMitchellClaimService/GetClaimMitchellFaultFault", Name="MitchellFault", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
        MitchellClaimClient.MitchellService.MitchellClaim GetClaim(string ClaimNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/GetClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/GetClaimResponse")]
        System.Threading.Tasks.Task<MitchellClaimClient.MitchellService.MitchellClaim> GetClaimAsync(string ClaimNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/GetClaimByDate", ReplyAction="http://tempuri.org/IMitchellClaimService/GetClaimByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MitchellClaimClient.MitchellService.MitchellFault), Action="http://tempuri.org/IMitchellClaimService/GetClaimByDateMitchellFaultFault", Name="MitchellFault", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
        System.Collections.Generic.List<string> GetClaimByDate(System.DateTime FromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/GetClaimByDate", ReplyAction="http://tempuri.org/IMitchellClaimService/GetClaimByDateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClaimByDateAsync(System.DateTime FromDate, System.DateTime ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/GetVehicleDetails", ReplyAction="http://tempuri.org/IMitchellClaimService/GetVehicleDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MitchellClaimClient.MitchellService.MitchellFault), Action="http://tempuri.org/IMitchellClaimService/GetVehicleDetailsMitchellFaultFault", Name="MitchellFault", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
        MitchellClaimClient.MitchellService.VehicleDetails GetVehicleDetails(string ClaimNumber, string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/GetVehicleDetails", ReplyAction="http://tempuri.org/IMitchellClaimService/GetVehicleDetailsResponse")]
        System.Threading.Tasks.Task<MitchellClaimClient.MitchellService.VehicleDetails> GetVehicleDetailsAsync(string ClaimNumber, string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/UpdateClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/UpdateClaimResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MitchellClaimClient.MitchellService.MitchellFault), Action="http://tempuri.org/IMitchellClaimService/UpdateClaimMitchellFaultFault", Name="MitchellFault", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
        void UpdateClaim(string updatexml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/UpdateClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/UpdateClaimResponse")]
        System.Threading.Tasks.Task UpdateClaimAsync(string updatexml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/DeleteClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/DeleteClaimResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MitchellClaimClient.MitchellService.MitchellFault), Action="http://tempuri.org/IMitchellClaimService/DeleteClaimMitchellFaultFault", Name="MitchellFault", Namespace="http://schemas.datacontract.org/2004/07/MitchellClaimService.DataContracts")]
        void DeleteClaim(string ClaimNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMitchellClaimService/DeleteClaim", ReplyAction="http://tempuri.org/IMitchellClaimService/DeleteClaimResponse")]
        System.Threading.Tasks.Task DeleteClaimAsync(string ClaimNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMitchellClaimServiceChannel : MitchellClaimClient.MitchellService.IMitchellClaimService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MitchellClaimServiceClient : System.ServiceModel.ClientBase<MitchellClaimClient.MitchellService.IMitchellClaimService>, MitchellClaimClient.MitchellService.IMitchellClaimService {
        
        public MitchellClaimServiceClient() {
        }
        
        public MitchellClaimServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MitchellClaimServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MitchellClaimServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MitchellClaimServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateClaim(string createxml) {
            base.Channel.CreateClaim(createxml);
        }
        
        public System.Threading.Tasks.Task CreateClaimAsync(string createxml) {
            return base.Channel.CreateClaimAsync(createxml);
        }
        
        public MitchellClaimClient.MitchellService.MitchellClaim GetClaim(string ClaimNumber) {
            return base.Channel.GetClaim(ClaimNumber);
        }
        
        public System.Threading.Tasks.Task<MitchellClaimClient.MitchellService.MitchellClaim> GetClaimAsync(string ClaimNumber) {
            return base.Channel.GetClaimAsync(ClaimNumber);
        }
        
        public System.Collections.Generic.List<string> GetClaimByDate(System.DateTime FromDate, System.DateTime ToDate) {
            return base.Channel.GetClaimByDate(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClaimByDateAsync(System.DateTime FromDate, System.DateTime ToDate) {
            return base.Channel.GetClaimByDateAsync(FromDate, ToDate);
        }
        
        public MitchellClaimClient.MitchellService.VehicleDetails GetVehicleDetails(string ClaimNumber, string vin) {
            return base.Channel.GetVehicleDetails(ClaimNumber, vin);
        }
        
        public System.Threading.Tasks.Task<MitchellClaimClient.MitchellService.VehicleDetails> GetVehicleDetailsAsync(string ClaimNumber, string vin) {
            return base.Channel.GetVehicleDetailsAsync(ClaimNumber, vin);
        }
        
        public void UpdateClaim(string updatexml) {
            base.Channel.UpdateClaim(updatexml);
        }
        
        public System.Threading.Tasks.Task UpdateClaimAsync(string updatexml) {
            return base.Channel.UpdateClaimAsync(updatexml);
        }
        
        public void DeleteClaim(string ClaimNumber) {
            base.Channel.DeleteClaim(ClaimNumber);
        }
        
        public System.Threading.Tasks.Task DeleteClaimAsync(string ClaimNumber) {
            return base.Channel.DeleteClaimAsync(ClaimNumber);
        }
    }
}
